// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using CinematicsXF.Core.Dto.MovieCredits;
//
//    var movieCreditsResultDto = MovieCreditsResultDto.FromJson(jsonString);

namespace CinematicsXF.Core.Dto.MovieCredits
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class MovieCreditsResultDto
    {
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public long? Id { get; set; }

        [JsonProperty("cast", NullValueHandling = NullValueHandling.Ignore)]
        public List<Cast> Cast { get; set; }

        [JsonProperty("crew", NullValueHandling = NullValueHandling.Ignore)]
        public List<Crew> Crew { get; set; }
    }

    public partial class Cast
    {
        [JsonProperty("cast_id", NullValueHandling = NullValueHandling.Ignore)]
        public long? CastId { get; set; }

        [JsonProperty("character", NullValueHandling = NullValueHandling.Ignore)]
        public string Character { get; set; }

        [JsonProperty("credit_id", NullValueHandling = NullValueHandling.Ignore)]
        public string CreditId { get; set; }

        [JsonProperty("gender", NullValueHandling = NullValueHandling.Ignore)]
        public long? Gender { get; set; }

        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public int? Id { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("order", NullValueHandling = NullValueHandling.Ignore)]
        public long? Order { get; set; }

        [JsonProperty("profile_path")]
        public string ProfilePath { get; set; }
    }

    public partial class Crew
    {
        [JsonProperty("credit_id", NullValueHandling = NullValueHandling.Ignore)]
        public string CreditId { get; set; }

        [JsonProperty("department", NullValueHandling = NullValueHandling.Ignore)]
        public Department? Department { get; set; }

        [JsonProperty("gender", NullValueHandling = NullValueHandling.Ignore)]
        public long? Gender { get; set; }

        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public int? Id { get; set; }

        [JsonProperty("job", NullValueHandling = NullValueHandling.Ignore)]
        public string Job { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("profile_path")]
        public string ProfilePath { get; set; }
    }

    public enum Department { Art, Camera, CostumeMakeUp, Crew, Directing, Editing, Lighting, Production, Sound, VisualEffects, Writing };

    public partial class MovieCreditsResultDto
    {
        public static MovieCreditsResultDto FromJson(string json) => JsonConvert.DeserializeObject<MovieCreditsResultDto>(json, CinematicsXF.Core.Dto.MovieCredits.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this MovieCreditsResultDto self) => JsonConvert.SerializeObject(self, CinematicsXF.Core.Dto.MovieCredits.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                DepartmentConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class DepartmentConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Department) || t == typeof(Department?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "Art":
                    return Department.Art;
                case "Camera":
                    return Department.Camera;
                case "Costume & Make-Up":
                    return Department.CostumeMakeUp;
                case "Crew":
                    return Department.Crew;
                case "Directing":
                    return Department.Directing;
                case "Editing":
                    return Department.Editing;
                case "Lighting":
                    return Department.Lighting;
                case "Production":
                    return Department.Production;
                case "Sound":
                    return Department.Sound;
                case "Visual Effects":
                    return Department.VisualEffects;
                case "Writing":
                default:
                    return Department.Writing;
            }
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Department)untypedValue;
            switch (value)
            {
                case Department.Art:
                    serializer.Serialize(writer, "Art");
                    return;
                case Department.Camera:
                    serializer.Serialize(writer, "Camera");
                    return;
                case Department.CostumeMakeUp:
                    serializer.Serialize(writer, "Costume & Make-Up");
                    return;
                case Department.Crew:
                    serializer.Serialize(writer, "Crew");
                    return;
                case Department.Directing:
                    serializer.Serialize(writer, "Directing");
                    return;
                case Department.Editing:
                    serializer.Serialize(writer, "Editing");
                    return;
                case Department.Lighting:
                    serializer.Serialize(writer, "Lighting");
                    return;
                case Department.Production:
                    serializer.Serialize(writer, "Production");
                    return;
                case Department.Sound:
                    serializer.Serialize(writer, "Sound");
                    return;
                case Department.VisualEffects:
                    serializer.Serialize(writer, "Visual Effects");
                    return;
                case Department.Writing:
                    serializer.Serialize(writer, "Writing");
                    return;
            }
        }

        public static readonly DepartmentConverter Singleton = new DepartmentConverter();
    }
}
